version: "3.8"

services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: intelligent_farm_broker
    ports:
      - "1883:1883"
      - "9001:9001" 
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    networks:
      - ditto-network

  mongodb:
    image: mongo:5
    container_name: intelligent_farm_db
    volumes:
      - mongo_data:/data/db
    networks:
      - ditto-network

  policies:
    image: eclipse/ditto-policies:latest
    dns_search: local
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/ditto
      - BIND_HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
    networks:
      ditto-network:
        aliases:
          - ditto-cluster

  things:
    image: eclipse/ditto-things:latest
    dns_search: local
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/ditto
      - BIND_HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
      - policies
    networks:
      ditto-network:
        aliases:
          - ditto-cluster

  things-search:
    image: eclipse/ditto-things-search:latest
    dns_search: local
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/ditto
      - BIND_HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
    networks:
      ditto-network:
        aliases:
          - ditto-cluster

  connectivity:
    image: eclipse/ditto-connectivity:latest
    dns_search: local
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/ditto
      - BIND_HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
    networks:
      ditto-network:
        aliases:
          - ditto-cluster

  gateway:
  image: eclipse/ditto-gateway:latest
  dns_search: local
  ports:
    - "8080:8080"

  environment:
    - ENABLE_PRE_AUTHENTICATION=true
    - DEVOPS_PASSWORD=foobar
    - BIND_HOSTNAME=0.0.0.0

  depends_on:
    - policies
    - things
    - things-search
    - connectivity

  networks:
    ditto-network:
      aliases:
        - ditto-cluster

networks:
  ditto-network:
    driver: bridge

volumes:
  mongo_data:
  mosquitto_data: