services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: smart_farm_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    networks:
      - ditto-network

  mongodb:
    image: mongo:5
    container_name: smart_farm_db
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - ditto-network

  policies:
    image: eclipse/ditto-policies:latest
    container_name: smart_farm_policies
    restart: unless-stopped
    dns_search: local
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/ditto
      - BIND_HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
    networks:
      ditto-network:
        aliases:
          - ditto-cluster

  things:
    image: eclipse/ditto-things:latest
    container_name: smart_farm_things
    restart: unless-stopped
    dns_search: local
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/ditto
      - BIND_HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
      - policies
    networks:
      ditto-network:
        aliases:
          - ditto-cluster

  things-search:
    image: eclipse/ditto-things-search:latest
    container_name: smart_farm_things_search
    restart: unless-stopped
    dns_search: local
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/ditto
      - BIND_HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
    networks:
      ditto-network:
        aliases:
          - ditto-cluster

  connectivity:
    image: eclipse/ditto-connectivity:latest
    container_name: smart_farm_connectivity
    restart: unless-stopped
    dns_search: local
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/ditto
      - BIND_HOSTNAME=0.0.0.0
    depends_on:
      - mongodb
    networks:
      ditto-network:
        aliases:
          - ditto-cluster

  gateway:
    image: eclipse/ditto-gateway:latest
    container_name: smart_farm_gateway
    restart: unless-stopped
    dns_search: local
    ports:
      - "8080:8080"
    environment:
      - ENABLE_PRE_AUTHENTICATION=true
      - DITTO_DEVOPS_SECURE_STATUS=false
      - BIND_HOSTNAME=0.0.0.0
      - JAVA_TOOL_OPTIONS=-Dditto.gateway.authentication.devops.password=foobar
    depends_on:
      - policies
      - things
      - things-search
      - connectivity
    networks:
      ditto-network:
        aliases:
          - ditto-cluster

networks:
  ditto-network:
    driver: bridge

volumes:
  mongo_data:
  mosquitto_data: