
"""

listener 1883 is mqtt port ...... esp32 and fastapi connect here
listener 9001 is websocket port ...... frontend{means dashboard} connect here
allow_anonymous true is allow to connect without username and password
persistence true is allow to save data when mosquitto restart
persistence_location /mosquitto/data/ is the location to save data when mosquitto restart
log_dest stdout is log to console so we can see what is happening in mosquitto





"""





listener 1883 0.0.0.0
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type all